version: "3.9"

services:
  ai-customer-support-agent:
    build: .
    container_name: ai-customer-support-agent

    ports:
      - "8000:8000"

    env_file:
      - .env

    restart: unless-stopped